### ISSUE TITLE
Create "getUsersRepeaters" sp and service

### ISSUE THREAD

**Issue by JoshuaCarroll** [ArkansasRepeaterCouncil/DataAccessWebservice#3]
Input: user's callsign, password, callsign to search for
Process:
- Verify login (execute login SP).. if false return nothing
- Query for all repeaters that have this callsign listed as a trustee
Output: for each result { id, callsign, frequency, city, last updated date }

**Comment by ae5au** [comment]
Created spGetUsersRepeaters.

Created DataAccessWebservice/GetUsersRepeaters/

Unable to test until @JoshuaCarroll deploys code update. CI doesn't seem to be enabled.

**Comment by JoshuaCarroll** [comment]
@ae5au, deployed.  Yeah, I haven't figured out how to implement CI with an Azure Function App yet.

**Comment by ae5au** [comment]
Corrected name of sp in service with 70c8c7d0a009aaca97120baeaa2ef59551f67692

Successfully tested service.
